import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import SealMark from "../components/SealMark.jsx";

export default function Terms() {
  return (
    <div className="min-h-screen bg-inkscale-50 dark:bg-inkscale-900 px-4 py-8">
      <div className="max-w-2xl mx-auto">
        <div className="flex items-center gap-3 mb-6">
          <SealMark size={36} tone="ink" />
          <p className="font-semibold text-inkscale-800 dark:text-white">QPaper AI</p>
        </div>

        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-burgundy hover:underline mb-6">
          <ArrowLeft size={15} /> Back
        </Link>

        <div className="bg-white dark:bg-inkscale-800 border border-inkscale-100/70 dark:border-white/10 rounded-2xl shadow-paper p-6 sm:p-8 space-y-6 text-sm text-inkscale-500 dark:text-inkscale-200">
          <div>
            <h1 className="text-xl font-semibold text-inkscale-800 dark:text-white mb-1">Terms of Use</h1>
            <p className="text-xs text-inkscale-300">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <p>
            QPaper AI is a student-built project for generating exam question papers using
            AI, aligned to Bloom's Taxonomy. It's provided as-is, for educational and
            personal use, without warranty of any kind. This isn't a commercial product
            backed by a company or legal team — please read these terms with that in mind.
          </p>

          <div>
            <h2 className="font-medium text-inkscale-800 dark:text-white mb-1">Using the service</h2>
            <p>
              You're responsible for the content you upload and the accounts you create.
              Don't upload material you don't have the right to use, and don't use the app
              to generate harmful, abusive, or illegal content.
            </p>
          </div>

          <div>
            <h2 className="font-medium text-inkscale-800 dark:text-white mb-1">AI-generated content</h2>
            <p>
              Questions and answers are generated by a third-party AI model (Google Gemini).
              The developer doesn't guarantee accuracy, correctness, or suitability of
              generated content for any exam or assessment — always review AI-generated
              questions before using them in a real exam.
            </p>
          </div>

          <div>
            <h2 className="font-medium text-inkscale-800 dark:text-white mb-1">Availability</h2>
            <p>
              This is a small, free, student-hosted project. It may go down, be slow to
              respond after inactivity, or have data reset during updates. It isn't
              intended for storing information you can't afford to lose.
            </p>
          </div>

          <div>
            <h2 className="font-medium text-inkscale-800 dark:text-white mb-1">Changes</h2>
            <p>
              These terms may be updated as the project evolves. Continued use after a
              change means you accept the updated terms.
            </p>
          </div>

          <div>
            <h2 className="font-medium text-inkscale-800 dark:text-white mb-1">Contact</h2>
            <p>
              Questions about these terms? Reach out at{" "}
              <a href="mailto:zensphnix@gmail.com" className="text-burgundy hover:underline">
                zensphnix@gmail.com
              </a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
